export type TranscriptType = "whatsapp" | "meeting";

import { EXTRACT_PROJECT_EVENTS_SCHEMA_TEXT } from "@/lib/transcripts/function-schema";

const BASE_PROJECT_EXTRACTION_PROMPT = `<overview>
You are a project status extraction assistant for Anjuman e Saifee Chicago Ashara Mubarak 1448H. Extract actionable project management events from the transcript.
</overview>

<data-model>
General guidance:
- Milestones are major deliverables, project phases, readiness checkpoints, budget lines, or large outcomes that a department is working toward. Examples: website ready for private review, AI helpdesk launched, site electrical plan completed, mawaid seating plan finalized. They usually have budgets associated. Milestones need to be MECE. We do not want overlapping milestones.
- Tasks are concrete work items that move a milestone forward and are connected to a milestone. Examples: call vendor, add ride-share details, create FAQ doc, confirm water source, review hotel page.
- Issues are blockers, risks, open questions, bugs, unclear decisions, or dependencies that may prevent progress. Examples: login/database error, unclear helpline handoff, unknown seating capacity, missing hotel rates, unresolved accommodation policy, or a neighboring site-use restriction.
</data-model>

<milestones>
- id: UUID primary key. Generated by the database; do not invent this for new milestones. Include it only when updating an existing milestone from the provided context.
- department_id: UUID of the department that owns the milestone. Use one of the department IDs supplied by upload context.
- title: Required short name of the milestone.
- description: Longer explanation of what the milestone means or what must be achieved.
- budget: Numeric budget amount, if mentioned. Use null when unknown.
- percent_complete: Integer progress value from 0 to 100. Use only when progress is stated or strongly implied.
- status: Allowed values are open, in_progress, blocked, complete.
- notes: Extra context, constraints, dependencies, owner names, or decisions.
- created_by, created_at, updated_at: System-managed. Do not output.

For milestone extraction, use these event types:
- milestone_created: A new major deliverable, readiness checkpoint, budget line, or project phase is identified. Send department_id, title, description, budget, percent_complete, status, notes. If you do not know a value, send null, especially for budget.
- milestone_updated: A known milestone receives progress, budget, status, scope, owner, timing, or decision updates. Always include id, then send any changed fields with the new value.
</milestones>

<tasks-and-issues>
- Tasks and issues are stored in the same table. A row is a task when item_type = task; it is an issue when item_type = issue.
- The event starts on June 15, 2026, so most tasks will need to be completed by then.
- Tasks and issues need to be connected to milestones through milestone_id. If you see a new task/issue but no corresponding milestone, also create the milestone. For new tasks/issues associated with existing milestones, pick the milestone_id that most closely relates to the work and belongs to the same department.
- User/assignee names in transcripts are usually friendly names, aliases, or WhatsApp display names. When creating or updating tasks/issues, use those names in assigned_to_alias when a person is assigned, mentioned as owner, or accepts ownership. Use the friendly name from the transcript; the review UI will map it to a system user later.

Tasks/issues use these database fields:
- id: UUID primary key. Generated by the database; do not invent this for new tasks/issues. Include it only when updating an existing task/issue from the provided context.
- department_id: UUID of the department that owns the task/issue.
- title: Required short name of the task or issue.
- description: Longer explanation, including source context, requirements, blockers, owner names, or acceptance criteria.
- status: Allowed values are open, in_progress, blocked, complete.
- assigned_to: UUID of assigned user. Leave null unless provided by context.
- created_by: System-managed. Do not output.
- source: Allowed values are call_transcript, whatsapp_agent, manual.
- due_date: Date deadline, if clearly stated or inferable from explicit transcript context.
- priority: Allowed values are low, medium, high.
- archived: System-managed. Do not output.
- milestone_id: UUID of the milestone this relates to.
- item_type: Allowed values are task or issue.
- created_at, updated_at: System-managed. Do not output.
- assigned_to_alias: Friendly name of the person this task should be assigned to based on the transcript.

For task/issue extraction, use these event types:
- task_created: A new action item or work item is identified.
- task_updated: A known task receives progress, owner, timing, scope, or status updates. Use status = complete when a task is completed.
- issue_created: A new blocker, risk, unresolved question, bug, dependency, or concern is identified.
- issue_updated: A known issue receives new context, owner, status, timing, or impact information.
- issue_resolved: An issue is answered, resolved, no longer blocking, or explicitly closed. Use status = complete.

When deciding between a task and an issue:
- If the message says something needs to be done, create/update a task.
- If the message reveals uncertainty, risk, missing information, disagreement, blocker, bug, or dependency, create/update an issue.
- If the issue is later answered or resolved, use issue_resolved.
- If a task is later accepted, started, or completed, use task_updated.
</tasks-and-issues>

<extraction-rules>
- Use existing milestones, tasks, and issues from context to identify updates before creating new records.
- Do not output member creation suggestions. Only use assigned_to_alias on task/issue events.
- Do not create events for greetings, jokes, thanks, repeated context, omitted media, pure links without action, or general FYI messages.
- Prefer fewer high-quality proposals over noisy extraction, but do not return an empty event list when clear project work, blockers, progress, or owners are present.
</extraction-rules>`;

export const FUNCTION_CALL_SCHEMA_SECTION = `<function-call-schema>
Call the extract_project_events function using this schema:
${EXTRACT_PROJECT_EVENTS_SCHEMA_TEXT}
</function-call-schema>`;

export const FIXED_TRANSCRIPT_PROMPT = `${BASE_PROJECT_EXTRACTION_PROMPT}

<transcript-type>
This upload is a WhatsApp export. Use message order, direct mentions, replies, and short acknowledgements like "sure", "yep", "I can", "I will", and "let me" to infer ownership or progress when the surrounding context is clear.
</transcript-type>

${FUNCTION_CALL_SCHEMA_SECTION}`;

export const FIXED_MEETING_PROMPT = `${BASE_PROJECT_EXTRACTION_PROMPT}

<transcript-type>
This upload is a meeting transcript or meeting minutes. Prioritize agenda decisions, action items, owners, due dates, risks, dependencies, budget approvals, and cross-department updates. Use the meeting date as context for relative due dates like "tomorrow", "next week", or "before waaz" when the transcript gives enough context.
</transcript-type>

${FUNCTION_CALL_SCHEMA_SECTION}`;

const defaultPrompt =
  "Focus on reviewable milestones, tasks, issues, status updates, owners, and deadlines. Convert unresolved operational questions into issues when they block progress. Convert accepted requests into task updates. Skip greetings, jokes, repeated context, omitted media, and pure FYI messages.";

const whatsappPromptSuffix =
  "For WhatsApp exports, infer ownership from mentions, direct replies, and short acknowledgements like sure/yep/I can. Treat message order as context, but do not invent owners when unclear.";

const meetingPromptSuffix =
  "For meeting transcripts, prioritize agenda decisions, action items, owners, due dates, risks, and dependencies. Treat follow-ups without owners as tasks with assigned_to_alias null.";

type DepartmentRule = {
  patterns: RegExp[];
  prompt: string;
};

const departmentRules: DepartmentRule[] = [
  {
    patterns: [/accommodation/],
    prompt: "Accommodation: Track utaro requests, hotel blocks, room counts, arrival/departure dependencies, form links, confirmation timing, negotiated rates, and guest communication. Flag uncertainty around accommodations or booking prerequisites as high-priority issues.",
  },
  {
    patterns: [/\bavr\b/, /audio/, /video/],
    prompt: "AVR: Track audio/video setup, waaz relay, screens, speakers, microphones, streaming, recording, power needs, testing windows, and coordination with site/electrical. Flag missing requirements or dependencies as issues.",
  },
  {
    patterns: [/communication/, /\bpr\b/, /public relations/],
    prompt: "Communication/PR: Track announcements, relay-site content, FAQs, guides, public/private publishing, review approvals, helpdesk scripts, and messaging to jamaats or mumineen. Flag unclear publication rules, privacy restrictions, or missing content as issues.",
  },
  {
    patterns: [/finance/, /procurement/, /qardan/, /najwa/, /shukr/],
    prompt: "Finance/Procurement/Qardan: Track budgets, quotes, purchase approvals, vendor commitments, payment follow-ups, booth/table needs, receipts, and procurement dependencies. Flag missing costs or approval blockers as issues.",
  },
  {
    patterns: [/fire safety/],
    prompt: "Fire Safety: Track inspections, permits, egress routes, tent/building occupancy, extinguishers, safety staffing, compliance approvals, and site hazards. Flag any unresolved safety/compliance question as high priority.",
  },
  {
    patterns: [/flow management/],
    prompt: "Flow Management: Track crowd routes, entrances/exits, capacity, queueing, seating movement, checkpoints, signage dependencies, and volunteer placement. Flag bottlenecks, capacity uncertainty, or unclear routes as issues.",
  },
  {
    patterns: [/\bhr\b/, /human resources/],
    prompt: "HR: Track volunteer recruitment, staffing gaps, schedules, role assignments, onboarding, training, credential needs, and availability confirmations. Flag unfilled roles or attendance uncertainty as issues.",
  },
  {
    patterns: [/\bit\b/, /\bits\b/],
    prompt: "IT/ITS: Track WhatsApp agent/helpdesk, dashboard, login/database bugs, automations, website crawler, access control, data integrations, phone-number permissions, manual handoff, analytics, and deployment/repo work. Flag bugs, missing content, handoff ambiguity, or access issues as high priority.",
  },
  {
    patterns: [/follow-up/],
    prompt: "Follow-up: Track pending callbacks, unanswered requests, owner confirmations, escalations, reminders, and closure status. Flag stale or ownerless follow-ups as issues.",
  },
  {
    patterns: [/mawaid/],
    prompt: "Mawaid: Track food counts, jaman timing, seating/rahat/chair blocks, partitions, serving flow, vendor/kitchen readiness, dietary needs, and coordination with site/sabeel. Flag count uncertainty or partition/seating blockers as issues.",
  },
  {
    patterns: [/medical/],
    prompt: "Medical: Track medical staffing, supplies, first-aid stations, emergency routes, patient-flow concerns, equipment, and shift coverage. Flag supply gaps or coverage risks as high priority issues.",
  },
  {
    patterns: [/mumineen reception/, /reception/],
    prompt: "Mumineen Reception: Track welcome desk setup, registration/check-in, guest guidance, information desk staffing, forms, badge/material handouts, and common attendee questions. Flag missing scripts or staffing gaps as issues.",
  },
  {
    patterns: [/nazafat/, /venue preparation/],
    prompt: "Nazafat/Venue Preparation: Track cleaning, venue readiness, setup/teardown, supplies, waste flow, room readiness, and dependencies on site/mawaid/flow. Flag readiness blockers as issues.",
  },
  {
    patterns: [/online niyaz/, /niyaz araz/],
    prompt: "Online Niyaz Araz: Track form readiness, payment/confirmation flow, data exports, support questions, reconciliation, and access issues. Flag broken forms or unclear submission status as issues.",
  },
  {
    patterns: [/photography/],
    prompt: "Photography: Track photo/video coverage plans, photographer assignments, access permissions, shot lists, delivery timelines, and coordination with PR/communications. Flag missing coverage or permission issues as blockers.",
  },
  {
    patterns: [/project management/, /\bpmo\b/],
    prompt: "Project Management: Track cross-team milestones, status reporting, PM meetings, dashboards, open blockers, ownerless tasks, escalation items, and daily updates. Convert unresolved cross-team questions into issues.",
  },
  {
    patterns: [/rahat support/, /\brahat\b/],
    prompt: "Rahat Support: Track seating/chair blocks, accessibility support, volunteer coverage, elderly/special-needs assistance, queue support, and coordination with mawaid/site/flow. Flag missing coverage or unclear seating assumptions as issues.",
  },
  {
    patterns: [/sabeel/],
    prompt: "Sabeel: Track sabeel location, snacks/tea/milk schedule, water coolers, hose bibs/water sources, refilling logistics, supplies, volunteer coverage, and site dependencies. Flag location or water-source uncertainty as issues.",
  },
  {
    patterns: [/scanning/],
    prompt: "Scanning: Track scanner/device readiness, access lists, check-in lanes, badge/QR workflows, staffing, troubleshooting, and data sync issues. Flag equipment or access failures as high priority.",
  },
  {
    patterns: [/security/],
    prompt: "Security: Track guard assignments, access control, entry/exit rules, incident response, restricted areas, crowd safety, and coordination with flow/fire safety. Flag security or access ambiguity as high priority.",
  },
  {
    patterns: [/site/, /construction/],
    prompt: "Site/Construction: Track HVAC, generators, electrical surveys/site plans, tent/seating capacity, water sources, sabeel placement, partitions, vendor calls, rentals, permits, inspections, map/site-layout updates, and dependencies with AV/mawaid/flow. Flag capacity, utility, vendor, or layout uncertainty as issues.",
  },
  {
    patterns: [/tazyeen/, /signage/, /signages/],
    prompt: "Tazyeen & Signages: Track decor/signage requirements, wayfinding signs, print/design approvals, placement maps, install timing, and dependencies from flow/site/communications. Flag missing copy, placement, or approval as issues.",
  },
  {
    patterns: [/\btnc\b/],
    prompt: "TNC: Track coordination requests, committee decisions, policy constraints, escalation items, and cross-functional dependencies. Flag unclear approvals or unresolved governance questions as issues.",
  },
  {
    patterns: [/istibsaar/],
    prompt: "Istibsaar: Track program/session readiness, participant needs, materials, room/setup requirements, volunteer support, and schedule changes. Flag missing resources or unclear ownership as issues.",
  },
  {
    patterns: [/hifz/],
    prompt: "Hifz: Track hifz program scheduling, participants, instructors, rooms, materials, and coordination needs. Flag schedule/resource gaps as issues.",
  },
  {
    patterns: [/translation/],
    prompt: "Translations: Track translation staffing, language needs, scripts/content, AV coordination, distribution channels, and review approvals. Flag missing translators or content readiness as issues.",
  },
  {
    patterns: [/transport/],
    prompt: "Transport: Track shuttles, drivers, vehicles, pickup/dropoff zones, ride-share guidance, airport/hotel routes, schedules, and communication to mumineen. Flag route/timing/capacity uncertainty as issues.",
  },
  {
    patterns: [/waaz talaqqi/, /talaqqi/],
    prompt: "Waaz Talaqqi: Track waaz relay/talaqqi logistics, seating assumptions, timing, access, AV/site dependencies, and attendee-flow questions. Flag capacity or readiness uncertainty as issues.",
  },
  {
    patterns: [/zakereen/],
    prompt: "Zakereen: Track zakereen schedules, assignments, room/stage needs, transport/accommodation dependencies, and content/program readiness. Flag missing confirmations as issues.",
  },
  {
    patterns: [/karamat/],
    prompt: "Karamat: Track karamat planning, materials, staffing, distribution, schedule, and coordination dependencies. Flag unclear ownership or supply gaps as issues.",
  },
];

export function getDefaultFlexiblePrompt(
  departmentName?: string | null,
  transcriptType: TranscriptType = "whatsapp",
): string {
  const normalized = departmentName?.trim().toLowerCase() ?? "";
  const matchingRule = departmentRules.find((rule) => rule.patterns.some((pattern) => pattern.test(normalized)))?.prompt;
  const transcriptRule = transcriptType === "meeting" ? meetingPromptSuffix : whatsappPromptSuffix;

  return [defaultPrompt, transcriptRule, matchingRule].filter(Boolean).join("\n\n");
}

export function getFixedPrompt(transcriptType: TranscriptType): string {
  return transcriptType === "meeting" ? FIXED_MEETING_PROMPT : FIXED_TRANSCRIPT_PROMPT;
}

export function buildTranscriptSystemPrompt(
  flexiblePrompt?: string | null,
  transcriptType: TranscriptType = "whatsapp",
): string {
  const fixedPrompt = getFixedPrompt(transcriptType);
  const trimmedFlexiblePrompt = flexiblePrompt?.trim();
  if (!trimmedFlexiblePrompt) {
    return fixedPrompt;
  }

  return `${fixedPrompt}

Department-specific extraction rules:
${trimmedFlexiblePrompt}`;
}
