-- A stable, numeric per-day id for niyaz_event_config (the "Niyaz day"). Used as the
-- registration_instance_id passed into the ashara_relay_double_rsvp Flow / button payloads — the
-- Flow is day-level (collects lunch + dinner counts), so it needs one numeric id per day, not a
-- per-meal rsvp_registration_instance UUID. Identity backfills existing rows (1..N) and auto-assigns
-- new ones; stable once assigned.

alter table public.niyaz_event_config
  add column if not exists day_id bigint generated by default as identity;

create unique index if not exists niyaz_event_config_day_id_key on public.niyaz_event_config (day_id);
